
@host=localhost:8080
@endpoint=/api/v1/tickets

### Exemplo GET todos os tickets
GET {{endpoint}}
Host: {{host}}

### Exemplo GET ticket por id
GET {{endpoint}}/1
Host: {{host}}

### Exemplo POST para criar ticket
POST {{endpoint}}
Host: {{host}}
Content-Type: application/json

{
  "acao": "Abrir chamado",
  "objeto": "Notebook",
  "detalhes": "Notebook não liga",
  "idCriador": 1,
  "idDestinatario": 2,
  "observadores": ["teste@email.com", "teste2@email.com"]
}

### Exemplo POST para criar ticket sem destinatário
POST {{endpoint}}
Host: {{host}}
Content-Type: application/json

{
  "acao": "Formatar",
  "objeto": "Computador",
  "detalhes": "Computador será vendido",
  "idCriador": 1,
  "observadores": ["teste3@email.com", "teste4@email.com"]
}

### Exemplo válido: Atualizar status para ANDAMENTO (com responsável)
PATCH {{endpoint}}/1/status
Host: {{host}}
Content-Type: application/json

{
  "status": "ANDAMENTO",
  "responsavelId": 2
}

### Exemplo válido: Cancelar ticket (com motivo)
PATCH {{endpoint}}/1/status
Host: {{host}}
Content-Type: application/json

{
  "status": "CANCELADO",
  "motivo": "Solicitação incorreta"
}

### Exemplo inválido: Cancelar ticket sem motivo
PATCH {{endpoint}}/1/status
Host: {{host}}
Content-Type: application/json

{
  "status": "CANCELADO"
}

### Exemplo inválido: ANDAMENTO sem responsável
PATCH {{endpoint}}/1/status
Host: {{host}}
Content-Type: application/json

{
  "status": "ANDAMENTO"
}

### Exemplo válido: Resolver ticket
PATCH {{endpoint}}/1/status
Host: {{host}}
Content-Type: application/json

{
  "status": "RESOLVIDO"
}
