# USER API ================================================================

@host=localhost:8080
@endpoint=/api/v1/users

### TODOS OS USUÁRIOS
GET {{endpoint}}
Host: {{host}}
Accept: application/json


### Get all users
# @name= getAllUsers

GET {{endpoint}}
Host: {{host}}
Accept: application/json

### Create a new valid User
# @name = createNewUser

POST {{endpoint}}
Host: {{host}}
Content-Type: application/json

{
    "email": "batata@gmail.com",
    "password": "1234RT56",
    "handle": "papas",
    "name": "Kartofel",
    "roles": [
        "ROLE_USER"
    ],
    "company": "potato inc"
}

### Create another valid User

POST {{endpoint}}
Host: {{host}}
Content-Type: application/json

{
    "email": "potato@gmail.com",
    "password": "123456789A",
    "handle": "batatinha",
    "name": "Potato",
    "roles": [
        "ROLE_USER"
    ],
    "company": "batata inc"
}


### Try and create an invalid User
# @name = tryCreateInvalidUser

POST {{endpoint}}
Host: {{host}}
Content-Type: application/json

{
    "email": "batata@potato.com",
    "password": "1234",
    "handle": "papas",
    "name": "Kartofel",
    "roles": [
        "ROLE_USER"
    ],
    "company": "potato inc"
}